name: CI MLOps Mini

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # 3. Cài dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc[all] mlflow

      # 4. Chạy pipeline DVC (train model)
      - name: Run DVC pipeline
        run: |
          dvc repro

      # 5. Upload model.pkl (nếu bạn lưu model riêng)
      - name: Upload trained model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: model/model.pkl

      # 6. Upload toàn bộ mlruns (MLflow artifacts)
      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: mlruns