name: CI MLOps Mini

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run training
        run: python src/train.py

      # 5. Upload model.pkl (nếu bạn lưu model riêng)
      - name: Upload trained model
        uses: actions/upload-artifact@v2
        with:
          name: trained-model
          path: model/model.pkl

      # 6. Upload toàn bộ mlruns (MLflow artifacts)
      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mlflow-artifacts
          path: mlruns